name: Java CI

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the job
jobs:
  build:
    # Specify the environment
    runs-on: ubuntu-latest

    # Steps to perform
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Set Java version
        distribution: 'temurin'

    - name: Build and Test
      run: |
        mvn clean install
        mvn test